what_was_that = "What was that?!"
lolis_are_cute = "I think lolis are cute, nya <3~"
this_is_text = "This is some text. This is more text. More text. Lolis. More text."
long_text = "あああ"
next_scene = "This is a new scene!"
isnt_that_cool = "Isn't that cool?!"
