package = "com.oxycode.myvisualnovel"
versionCode = 2
versionName = "1.0.3"
languages = {"ja", "en"}
resolution = "1280x720" -- Your videos & backgrounds should be this big, please use 16:9
localizationPath = "localization"
assetPaths = {
    voice = "audio/voice",
    music = "audio/music",
    sound = "audio/sound",
    video = "audio/video",
    text = "text",
    image = "image",
    character = "script/character",
    screen = "script/screen",
    scene = "script/scene"
}
title = R.text.common.title
author = R.text.common.author
